env = Environment()

env.Append(CXXFLAGS = ['-O3', '-Wall', '-Wextra'])
env.Append(CPPPATH = ['.', 'common'])

env.Library('dnes', ['nes.cc',
                     'cpu.cc',
                     'ppu.cc',
                     'apu.cc',
                     'cart.cc',
                     'common/file.cc',
                     'common/ines.cc',
                     'common/nes_exception.cc',
                     'mappers/mapper_base.cc',
                     'mappers/cnrom.cc',
                     'mappers/mmc1.cc',
                     'mappers/mmc3.cc',
                     'mappers/nrom.cc',
                     'mappers/uxrom.cc',
                     'audio/audio_backend.cc',
                     'audio/iaudio_platform.cc',
                     'audio/alsa_platform.cc',
                     'video/gl_util.cc',
                     'video/video_backend.cc',
                     'video/igl_platform.cc',
                     'video/glx_platform.cc'])

env.Install('#build/include/dnes', 'nes.h')
env.Install('#build/lib', 'libdnes.a')

env.Alias('core', './libdnes.a')